name: sampahku
description: Smart Waste Classifier

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # TensorFlow Lite - PENTING untuk ML!
  tflite_flutter: ^0.10.4

  # Image Processing
  image: ^4.0.17
  image_picker: ^1.0.4

  # Path Management
  path_provider: ^2.1.1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - assets/model.tflite
    - assets/labels.txt